### ISSUE TITLE
hi! awesome plugin! are you "there" (or "here"?) ?

### ISSUE THREAD

**Issue by m-faith** [EvWilson/slimux.nvim#1]
***awesome looking plugin!!!***

**Comment by m-faith** [comment]
whoops - posted accidentally before typing.

I was very excited to see your plugin posted several months ago https://www.reddit.com/r/neovim/comments/13r10ih/slimuxnvim_simple_plugin_to_send_text_to_tmux/ and I finally got a round to trying it out last night.

With your asciinema cast "archived" and not available I wonder if you're still here and intending to develop this plugin further?

I found a bug with `"` being removed from the code when it's sent to the other tmux pane, and my own coding skills *might (again, maybe)* be getting to the point where I could be capable of fixing something like that...  though unfortunately it might be less work for me to configure a different method for running my lua code (paritcularly since sending to a different tmux pane means sending to a repl and all the lua repls are quite deficient and I think there are some good nvim plugins for running lua code).

**Comment by m-faith** [comment]
I was really excited to see a slime-like plugin specifically for tmux with the config instructions already in `lua`!

**Comment by m-faith** [comment]
If I'm sending to a pane running `ptpython` (a nicer python repl) I need to toggle *paste mode* (in ptpython, toggled via `F6`) before running `slimux.send_paragraph_text()` (so the formatting is correct, otherwise extra tabs are inserted which breaks python) and after `slimux.send_paragraph_text()` as well before ptpython can run the code.

I imagine the way to handle this would *not* be in this plugin itself, but to write a lua config function that does an extra `tmux send-keys` before and after the call to `slimux.send...` though I'm bad at this stuff and so don't have any idea whether some accommodation for this kind of scenario would be an appropriate addition (perhaps an extra slimux config option for sending prefix/suffix keystrokes???). But anyway, while testing, I thought it might be worth sharing this here.

**Comment by m-faith** [comment]
Anyhow.  **Thanks for the plugin!!!** I'm so bad at coding that just reading `lua/slimux/init.lua` was educational for me. Thanks again!

**Comment by abieler** [comment]
:wave: i ran into the same issue as you. 
with some help of chat-gpt i opened i [PR](https://github.com/EvWilson/slimux.nvim/pull/2) to this repository.
in the meantime you can also use my [fork,](https://github.com/abieler/slimux.nvim) 
by replacing 'EvWilson/slimux.nvim' with 'abieler/slimux.nvim'

**Comment by EvWilson** [comment]
Hey there! I'm so sorry, clearly I need to turn on notifications for my personal repos - this is a bit of a new experience for me. 😅 
Will happily steal some of @abieler's work and reincorporate it into this repo - pretty sure I ran into this issue when throwing around `curl` requests at work. Thanks so much for filing an issue!

**Comment by abieler** [comment]
cool! maybe would be convenient to give the user a way to configure/customize which characters to escape.

for my case where i tested with the julia REPL the "trailing-semicolon" actually is not desirable, but i think the $ should be escaped.
so if one can provide a list with characters to escape that would be :ok_hand: 
or full "profiles" that come pre-filled, depending if you send it to a python repl or whatever :man_shrugging: 

just spitting ideas here, no pressure :grin: 
cheers and thanks

**Comment by EvWilson** [comment]
Hey again! As mentioned in the other PR (thanks again for opening it!) I've gone ahead and taken a stab at implementing the suggested changes over in https://github.com/EvWilson/slimux.nvim/pull/3. This includes providing an overridable array that you can tailor to your use case, inserting a backslash before any of the strings included.

Let me know either here or there if this takes care of your issues, I'll be keeping an eye on both spaces! Will close this issue out once it looks like there's something workable for everyone there.

**Comment by EvWilson** [comment]
Just merged changes from https://github.com/EvWilson/slimux.nvim/pull/3, which should hopefully fix any issues! If anything else pops up that's giving problems, feel free to comment here or open another issue and I'll take a look into it.
