### ISSUE TITLE
feature: for use in making screen/term/asciicast, send lines character-by-character

### ISSUE THREAD

**Issue by m-faith** [EvWilson/slimux.nvim#4]
I'm making a recording of a terminal session using https://asciinema.org/ (recording will be an "asciicast" I guess?) and would love to be able to send the characters 1-by-1 instead of the whole line in one blob :)

**Comment by m-faith** [comment]
The idea is to emulate the typing, and to save people from watching me correct my typos. I guess a configurable *delay* to create spacing between the "keypresses" would make sense.

**Comment by m-faith** [comment]
I wonder if I'll try to make this myself. I was excited to see your work at https://github.com/EvWilson/slimux.nvim/pull/3 :)

**Comment by EvWilson** [comment]
Hey @m-faith! Good to see you again, thanks for the kind words.
To your point, I think it should be entirely possible to accomplish the above by creating another `M.__send` that splits the given text and sends the characters one at a time, with a sleep between them.

Happy to let you take a stab at it! Otherwise, just let me know and I'd be happy to help.

**Comment by m-faith** [comment]
oh gee... if you'd like to I'd be thrilled!  I'd love to see how you do it!

I'm struggling with `string.format()` and `vim.fn.systemlist` and I think a couple other points. I could probably figure this out eventually but somewhat impaired here.

**Comment by m-faith** [comment]
Oh... a delay inbetween keypresses, and I think a *pause* after the keys are sent but before *Enter* to allow time for the person viewing the asciicast (a student in this case) to read the command before it gets run...

So for example when the command is something like:

`sed -En '/:vim:/,/(^---|^:[a-z]*:)/p' docs/202*.mkd`

...and things that look complicated to a beginner, it'd be nice to be able to configure a pause, allowing student to read it, before `Enter` gets sent and then the command disappears as the output fills the terminal screen.

**Comment by EvWilson** [comment]
Hey @m-faith, mind checking out the branch in the PR linked above and seeing if it works for your use case?

**Comment by m-faith** [comment]
Oh, awesome, can't wait to try this out!

**Comment by m-faith** [comment]
bytheway do you know of https://github.com/rockerBOO/awesome-neovim?tab=readme-ov-file#code-runner and https://dotfyle.com/neovim/plugins/trending?page=1&q=tmux ..? Thought I'd mention in case you'd like to add slimux to those lists :)

**Comment by EvWilson** [comment]
Thanks so much for the mention of those spots! I've seen lists like them before but haven't thought to submit anything to them. I suppose I've just considered slimux to be small enough in scope before now that other people wouldn't be interested, but these past couple issues are clearly proving me wrong 😅. I'll have to see if those maintainers would like to have it!

**Comment by m-faith** [comment]
Hi! I'm back finally, library's closed on weekends here and gee now I don't understand lazy.nvim enough to specify the branch to test ... 

I've got:

```lua
  {
    'EvWilson/slimux.nvim',
    config = function()
      local slimux = require('slimux')
      slimux.setup({
        target_socket = slimux.get_tmux_socket(),
        target_pane = string.format('%s.2', slimux.get_tmux_window()),
        -- note: to live/reconfigure tmux target pane, run:
        --       lua require('slimux').configure_target_pane('8.2')
      })
      vim.keymap.set('v', '<leader>r', ':lua require("slimux").send_highlighted_text()<CR>',
        { desc = 'Send currently highlighted text to configured tmux pane' })
      vim.keymap.set('n', '<leader>r', ':lua require("slimux").send_paragraph_text()<CR>',
        { desc = 'Send paragraph under cursor to configured tmux pane' })
    end
  },
```

...do you know how I can specify the per-character branch?

I was able to lazy-update and get the string escape fixes --- awesome!

**Comment by m-faith** [comment]
omg. the lazy.nvim README. I got the updated branch...  and got it working ... I have to manually run `:lua require('slimux')` in nvim... is this expected?

This is awesome. I'm excited about this new feature!!!

**Comment by EvWilson** [comment]
So if you want `lazy.nvim` to be added automatically in the config function, you'll want to bind the new functions as well. So, below your current keymaps in the config:
```lua
vim.keymap.set('v', '{{YOUR KEYBIND HERE}}', ':lua require("slimux").send_highlighted_text_with_delay_ms()<CR>',
        { desc = 'Send currently highlighted text to configured tmux pane, with per-character delay' })
      vim.keymap.set('n', '{{YOUR KEYBIND HERE}}', ':lua require("slimux").send_paragraph_text_with_delay_ms()<CR>',
        { desc = 'Send paragraph under cursor to configured tmux pane, with per-character delay' })
```
Note the `{{YOU KEYBIND HERE}}` portion, where you'll want to configure what you want the functions bound to (or you can do something else, like creating a command: https://neovim.io/doc/user/api.html#api-command). This will let you call these functions without having to do the `:lua require('slimux')` rigamarole.

Besides that though, is it working well enough for you? If so, I'm going to go ahead and merge it.

**Comment by EvWilson** [comment]
Hey @m-faith, I'm going to go ahead and merge this change, just to get it all out there. Hope it's been working for you, feel free to open another issue if you need any tweaks!
