### ISSUE TITLE
Send currently highlighted text sends full line

### ISSUE THREAD

**Issue by hendr1km** [EvWilson/slimux.nvim#6]
the send highlighted text function currently sends the full line. Is there a possibility to send only a specific selection (without including the full line) to the other tmux pane?

**Comment by EvWilson** [comment]
Hey @hendr1km! Thanks for reaching out. I think you've correctly called out a bug here, so I went ahead and created a fix for it here: https://github.com/EvWilson/slimux.nvim/pull/7. If you'd like to check it out and make sure it works for what you're looking for, please go ahead. I'll probably merge it pretty quickly (next day or so) regardless.

Thanks for the issue! Apologies it came up, as mentioned in the PR I pretty much just always grab the whole line, so I was pretty blind to this one.

**Comment by EvWilson** [comment]
Hey @hendr1km, went ahead and merged the PR mentioned above. Hope that solves your problem, going ahead and closing this issue for now. Let me know if there's anything else you'd like changed!

**Comment by hendr1km** [comment]
Thanks a lot! @EvWilson
